generator:
  class: sfPropelGenerator
  param:
    model_class:           mobitvabotNews
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              mobitvabotNews
    plural:                mobitvabotNewss
    route_prefix:          mobitvabot_news
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
