<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/01 00:51:11

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=mobitva;host=localhost',
  'username' => 'root',
  'password' => 123456,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
