<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/25 05:25:38
sfConfig::add(array(
  'app_bot_price' => 45,
  'app_bot_pre_end_discount' => 10,
  'app_bot_add_char_price' => 10,
  'app_bot_add_char_mounts_price' => 20,
  'app_bot_message_need_more_money' => 'У Вас недостаточно средств, для выполнения данной операции',
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_sf_captchagd_image_width' => 100,
  'app_sf_captchagd_image_height' => 30,
  'app_sf_captchagd_chars' => '123456789',
  'app_sf_captchagd_length' => 4,
  'app_sf_captchagd_font_size' => 18,
  'app_sf_captchagd_force_new_captcha' => true,
  'app_sf_captchagd_font_color' => array (
  0 => '252525',
  1 => '8b8787',
  2 => '550707',
  3 => '3526E6',
  4 => '88531E',
),
  'app_sf_captchagd_fonts' => array (
  0 => 'akbar/akbar.ttf',
  1 => 'brushcut/BRUSHCUT.TTF',
  2 => 'molten/molten.ttf',
  3 => 'planet_benson/Planetbe.ttf',
  4 => 'whoobub/WHOOBUB_.TTF',
),
  'app_sf_captchagd_background_color' => 'DDDDDD',
  'app_sf_captchagd_border_color' => 0,
));
