<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/01 01:44:42
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'payment' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
