generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroupPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardGroupPermission
    plural:                sfGuardGroupPermissions
    route_prefix:          sf_guard_group_permission
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
