<?php


/**
 * Skeleton subclass for representing a row from the 'botconfig_relations' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/25/13 01:40:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class botconfigRelations extends BasebotconfigRelations {

} // botconfigRelations
