<?php

/**
 * Skeleton subclass for representing a row from the 'license' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/05/13 16:52:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class license extends Baselicense {

  public function isActive() {
    if ($this->getDateEnd() < date('Y-m-d H:i:s', time())) {
      return false;
    }
    return true;
  }

}

// license
