<?php


/**
 * Skeleton subclass for representing a row from the 'license_char' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/06/13 01:24:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class licenseChar extends BaselicenseChar {

} // licenseChar
