<?php

/**
 * Skeleton subclass for performing query and update operations on the 'llicense_chars_places' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/13 07:03:05
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class licenseCharsPlacesPeer extends BaselicenseCharsPlacesPeer {

  public static function getCountCharsByLicenseId($licenseId) {

    $c = new Criteria();
    $c->add(self::LICENSE_ID, $licenseId);
    $c->add(self::DATE_END, date('Y-m-d', time()), Criteria::GREATER_EQUAL);
    $results = self::doSelect($c);

    $charsCount = 0;
    foreach ($results as $licenseCharsPlaces) {
      $charsCount += $licenseCharsPlaces->getCharsCount();
    }

    // изначально можно включить одну копию программы. 
    // А все привязанные к лицензии "места для персонажей" - это улучшение лицензии.
    // Поэтому возвращаем полученное значение плюс 1.
    return $charsCount + 1; 
  }

}

// licenseCharsPlacesPeer
