<?php

/**
 * Skeleton subclass for performing query and update operations on the 'license' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/05/13 16:52:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class licensePeer extends BaselicensePeer {

  
  
  public static function getUserLicense($user_id) {

    $c = new Criteria();
    $c->add(self::USER_ID, $user_id);
    $c->setLimit(1);
    return self::doSelectOne($c);
  }

}

// licensePeer
