<?php


/**
 * Skeleton subclass for representing a row from the 'mobitvabot_ticket' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/05/12 21:37:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class mobitvabotTicket extends BasemobitvabotTicket {

	/**
	 * Initializes internal state of mobitvabotTicket object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // mobitvabotTicket
