<?php


/**
 * Skeleton subclass for representing a row from the 'mobitvabot_transaction' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/05/12 21:37:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class mobitvabotTransaction extends BasemobitvabotTransaction {

} // mobitvabotTransaction
