generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUserGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUserGroup
    plural:                sfGuardUserGroups
    route_prefix:          sf_guard_user_group
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
